### ISSUE TITLE
希望支持发起Midjourney作画

### ISSUE THREAD

**Issue by buqiuwenda** [XdpCs/wujiesdk#50]
接口文档链接：https://apifox.com/apidoc/shared-ecc069df-a9d5-4c86-b723-6dcd5cc79f81/api-202034793
希望支持该接口，谢谢

**Comment by XdpCs** [comment]
好 我看一下文档细节

**Comment by XdpCs** [comment]
@buqiuwenda 先使用master 分支 测试一下是否可以使用 如果没问题后 我会release新的版本 我自己本地测没什么问题

**Comment by buqiuwenda** [comment]
@XdpCs Midjourney作画接口测试通过

**Comment by XdpCs** [comment]
> @XdpCs Midjourney作画接口测试通过

release v 1.0.14
